version: '3'
services:
  app:
    build:
      context: .
    image: my-app-image
    ports:
      - "80:80"
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
